"""initial schema

Revision ID: 7393a246ae62
Revises: 
Create Date: 2026-03-31 16:11:53.019424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7393a246ae62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatrooms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('chatroom_participants',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatroom_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chatroom_id', name='unique_user_chatroom')
    )
    op.create_table('messages',
    sa.Column('message_text', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatroom_id', sa.String(length=36), nullable=False),
    sa.Column('is_reply', sa.Boolean(), nullable=False),
    sa.Column('parent_message_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chatroom_id', 'messages', ['chatroom_id'], unique=False)
    op.create_index('ix_messages_parent_message_id', 'messages', ['parent_message_id'], unique=False)
    op.create_index('ix_messages_user_id', 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_user_id', table_name='messages')
    op.drop_index('ix_messages_parent_message_id', table_name='messages')
    op.drop_index('ix_messages_chatroom_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('chatroom_participants')
    op.drop_table('users')
    op.drop_table('chatrooms')
    # ### end Alembic commands ###
